### ISSUE TITLE
npm package is broken

### ISSUE THREAD

**Issue by niblius** [ijsnow/studiojs#1]
Hi!
I am just letting you know that the npm package doesn't contain lib/ folder. I managed to make the package working by simply running "npm install" in the node_modules/recorder-js folder. Please fix when you will have time.

Best regards,
a community member.

**Comment by ijsnow** [comment]
Hey! Thanks for the heads up! I had actually noticed but hadn't gotten around to fixing it yet. Didn't think anyone would be interested in using this so quickly! Glad you got it working for now. Let me know what you think of it

**Comment by ijsnow** [comment]
I'll fix the publishing tomorrow

**Comment by niblius** [comment]
Everything works cool, both the recorder and wave-stream! Thanks for you work!

**Comment by ijsnow** [comment]
Fixed with `1.0.7`
