### ISSUE TITLE
How can I upload audio to server?

### ISSUE THREAD

**Issue by nvlong198** [ijsnow/studiojs#8]
your example at  [here](https://github.com/ijsnow/studiojs/blob/master/examples/reactjs/src/App.js) can download **react-audio.wav**
How can I POST file  **react-audio.wav** to the server? which kind of variable/object using for?
Thank you.

**Comment by ijsnow** [comment]
Hi! I wasn't aware people were using this library still! Cool!

The library just gives you back a `Blob` which can be treated as a raw file. Uploading the file to a server is separate. [This article](https://websnippet.io/post/html5-file-upload-without-jquery/) might help. If not, there is other information out there on the internet for this.

**Comment by ijsnow** [comment]
You'll be using [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) which can be sent as `multipart/form-data` with [XMLHttpRequest.send()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send).

Hope this helps. But as the README mentions, I haven't worked on this in quite some time and I don't plan on it so don't expect speedy replies :)
